# permissions for end users to view sealedvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealedvolume-viewer-role
rules:
- apiGroups:
  - keyserver.kairos.io
  resources:
  - sealedvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keyserver.kairos.io
  resources:
  - sealedvolumes/status
  verbs:
  - get
