# permissions for end users to edit sealedvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealedvolume-editor-role
rules:
- apiGroups:
  - keyserver.kairos.io
  resources:
  - sealedvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keyserver.kairos.io
  resources:
  - sealedvolumes/status
  verbs:
  - get
